import { NextAuthProvider } from '@/components/Provider'
import './globals.css'
import { NavBar } from '@/components/NavBar'


export const metadata = {
  title: 'Promptnetwork',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-r from-slate-900 to-zinc-900 text-white'>
        <NextAuthProvider>
          <main className='container mx-auto'>
            <NavBar />
            {children}
          </main>
        </NextAuthProvider>
      </body>
    </html>
  )
}
